/**
 * useVoiceCoach
 * This is a React Hook that gives the AI Coach a "voice".
 * It takes the text feedback generated by the CoachingEngine (e.g., "Bend your knee")
 * and uses the browser's built-in Web Speech API to read it out loud.
 */
import { useRef, useCallback } from 'react';
import { VOICE } from '@shared/constants';

export function useVoiceCoach(enabled = true) {
  // We keep track of the last time we said a specific phrase.
  // This prevents the coach from repeating "Bend your knee" 5 times a second.
  const lastSpoken = useRef<Map<string, number>>(new Map());
  
  // This holds the actual speech engine
  const synthRef   = useRef<SpeechSynthesis | null>(null);

  // Initialize the speech engine if we are in a browser environment
  if (typeof window !== 'undefined' && !synthRef.current) {
    synthRef.current = window.speechSynthesis;
  }

  /**
   * SPEAK
   * Pass a string of text here to make the coach say it.
   */
  const speak = useCallback((text: string) => {
    if (!enabled || !synthRef.current) return; // Don't speak if muted
    
    const now  = Date.now();
    const last = lastSpoken.current.get(text) ?? 0;
    
    // COOLDOWN LOGIC: Has it been long enough since we last said this exact phrase?
    if (now - last < VOICE.COOLDOWN_MS) return;
    
    // Remember that we just said this phrase
    lastSpoken.current.set(text, now);

    // Create a new "utterance" (the thing we want to say)
    const utt       = new SpeechSynthesisUtterance(text);
    utt.rate        = VOICE.RATE;   // How fast?
    utt.pitch       = VOICE.PITCH;  // How high/low?
    utt.volume      = VOICE.VOLUME; // How loud?
    utt.lang        = VOICE.LANG;   // What language/accent?
    
    // Cancel whatever the coach is currently saying so they can immediately give the new feedback
    synthRef.current.cancel(); 
    
    // Speak the new feedback
    synthRef.current.speak(utt);
  }, [enabled]);

  /**
   * CANCEL
   * Immediately stops the coach from talking.
   */
  const cancel = useCallback(() => {
    synthRef.current?.cancel();
  }, []);

  return { speak, cancel };
}
